AWSTemplateFormatVersion: '2010-09-09'

Description: Template to deploy auto invest instance

Metadata:
  cfn-lint:
    config:
      ignore_checks:
      - W1001
      - E2507
      - W3005
      - E3002
      - E3012

Parameters:

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the subnet in the VPC

  UserIp:
    Type: String
    Description: The IP address that the user is currently using to deploy the instance

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The key pair to enable ssh onto the intstance

  AmiId:
    Description: 
      The name of the AMI id to use for running the auto invest app
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

  InstanceType:
    Description: 
      The instance type the SQS monitor will be using
    Type: String
    Default: t3.micro

  SettingsPrefix:
    Type: String
    Description: The parameter store prefix for the settings
    Default: 'auto-invest'

  LogRetention:
    Type: Number
    Description: The number of days to keep the cloudwatch logs
    Default: 30

  LogGroupPrefix:
    Type: String
    Description: The Prefix in front of the log group name
    Default: auto-invest

  S3ArtifactBucket:
    Type: String
    Description: The Bucket the deployment artifacts are stored
    Default: insecure-artifacts-93648082bbed41458cac8d7814803d3c

  ArtifactPath:
    Type: String
    Description: The relative S3 path in the artifact bucket location for the artifacts
    Default: /auto-invest

  EnvName:
    Type: String
    Description: The environment name 
    Default: dev
    
Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access for VPN users
      SecurityGroupIngress:
        - FromPort: 22
          IpProtocol: tcp
          ToPort: 22
          CidrIp: !Sub "${UserIp}/32"
        - FromPort: 5000
          IpProtocol: tcp
          ToPort: 5000
          CidrIp: !Sub "${UserIp}/32"
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: '0.0.0.0/0'
      VpcId: !Ref VPCId

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: "1"
      MinSize: "0"
      DesiredCapacity: "1"
      VPCZoneIdentifier: 
        - !Ref SubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber

  ContractDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Symbol
          AttributeType: S
      TableName: auto-invest-contract
      KeySchema:
        - AttributeName: Symbol
          KeyType: HASH
        - AttributeName: Symbol
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST  

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole
  
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: auto-invest-role
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: auto-invest-role-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - autoscaling:*
                  - cloudwatch:*
                  - ec2:Describe*
                Resource: "*"
              - Effect: Allow
                Action:
                  - S3:Get*
                Resource: !Sub "arn:aws:s3:::${S3ArtifactBucket}${ArtifactPath}/*"               
              - Effect: Allow
                Action:
                  - ssm:GetParametersByPath
                  - ssm:GetParameters
                  - ssm:GetParameter
                  - ssm:ListTagsForResource
                Resource:
                  - arn:aws:ssm:*:*:parameter/AmazonCloudWatch-*
                  - !Sub "arn:aws:ssm:*:*:parameter/${EnvName}/${SettingsPrefix}/*"
                  - !Sub "arn:aws:ssm:*:*:parameter/${EnvName}/${SettingsPrefix}"
              - Effect: Allow
                Action:
                  - kms:Decrypt
                Resource: 
                  - arn:aws:kms:*:*:key/alias/aws/ssm

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: auto-invest-launch-template
      LaunchTemplateData:
        InstanceType: !Ref InstanceType
        ImageId: !Ref AmiId
        KeyName: !Ref KeyPair
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            SubnetId: !Ref SubnetId
            Groups:
              - !Ref SecurityGroup
            DeleteOnTermination: true
        InstanceMarketOptions:     
          MarketType: spot
          SpotOptions:
            SpotInstanceType: "one-time"
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -x
            export IBEAM_INPUTS_DIR=/srv/inputs
            export IBEAM_OUTPUTS_DIR=/srv/outputs
            export ECR_REGISTRY=public.ecr.aws/x9x1s8n0
            export ECR_REPO=busyweb/ibeam

            rpm -Uvh https://packages.microsoft.com/config/centos/7/packages-microsoft-prod.rpm
            yum update -y
            yum install -y \
                java-1.8.0-openjdk \
                aspnetcore-runtime-6.0 \
                unzip \
                amazon-cloudwatch-agent \
                jq \
                docker

            systemctl enable docker.service
            systemctl start docker.service
             
            mkdir /srv
            mkdir $IBEAM_INPUTS_DIR
            mkdir $IBEAM_OUTPUTS_DIR

            chmod 577 $IBEAM_INPUTS_DIR
            chmod 577 $IBEAM_OUTPUTS_DIR

            aws s3 cp s3://${S3ArtifactBucket}${ArtifactPath}/api.ibkr.cer api.ibkr.cer --region ${AWS::Region}
            cp api.ibkr.cer /etc/ssl/certs/api.ibkr.cer

            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
            export PRIVATE_IPV4=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/local-ipv4)
            export PRIVATE_HOSTNAME=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/local-hostname)

            export IBEAM_ACCOUNT=$(aws ssm get-parameter --name /${EnvName}/${SettingsPrefix}/ibeam_account --with-decryption --region ${AWS::Region} | jq -r '.Parameter.Value')
            export IBEAM_PASSWORD=$(aws ssm get-parameter --name /${EnvName}/${SettingsPrefix}/ibeam_password --with-decryption --region ${AWS::Region} | jq -r '.Parameter.Value')

            cat <<'EOF' > $IBEAM_INPUTS_DIR/conf.yaml.tmpl
              ip2loc: "US"
              proxyRemoteSsl: true
              proxyRemoteHost: "https://api.ibkr.com"
              listenPort: 5000
              listenSsl: true
              svcEnvironment: "v1"
              sslCert: "cacert.jks"
              sslPwd: "password"
              authDelay: 3000
              portalBaseURL: ""
              serverOptions:
                  blockedThreadCheckInterval: 1000000
                  eventLoopPoolSize: 20
                  workerPoolSize: 20
                  maxWorkerExecuteTime: 100
                  internalBlockingPoolSize: 20
              cors:
                  origin.allowed: "*"
                  allowCredentials: false
              webApps:
                  - name: "demo"
                    index: "index.html"
              ips:
                allow:
                  - 192.*
                  - 131.216.*
                  - 127.0.0.1
                  - 0.0.0.0
                  - ${UserIp}
                  - ${!PRIVATE_IPV4}
                deny:
                  - 212.90.324.10
            EOF
            touch $IBEAM_INPUTS_DIR/conf.yaml
            chmod 777 $IBEAM_INPUTS_DIR/conf.yaml
            PRIVATE_IPV4=$PRIVATE_IPV4 envsubst < $IBEAM_INPUTS_DIR/conf.yaml.tmpl > $IBEAM_INPUTS_DIR/conf.yaml

            cat <<'EOF' > $IBEAM_INPUTS_DIR/san.tmpl
                [req]
                default_bits = 2048
                distinguished_name = req_distinguished_name
                req_extensions = req_ext
                x509_extensions = v3_req
                prompt = no

                [req_distinguished_name]
                countryName = XX
                stateOrProvinceName = N/A
                localityName = N/A
                organizationName = IBeam
                commonName = IBeam

                [req_ext]
                subjectAltName = @alt_names

                [v3_req]
                subjectAltName = @alt_names

                [alt_names]
                IP.1 = ${!PRIVATE_IPV4}
                DNS.1 = localhost
            EOF

            cat <<'EOF' > $IBEAM_INPUTS_DIR/generate-cert.sh
                touch $IBEAM_INPUTS_DIR/san.cnf
                chmod 777 $IBEAM_INPUTS_DIR/san.cnf
                PRIVATE_IPV4=$PRIVATE_IPV4 PRIVATE_HOSTNAME=$PRIVATE_HOSTNAME envsubst < $IBEAM_INPUTS_DIR/san.tmpl > $IBEAM_INPUTS_DIR/san.cnf

                openssl req -x509 -days 730 -newkey rsa:2048 -keyout $IBEAM_INPUTS_DIR/key.pem -out $IBEAM_INPUTS_DIR/cert.pem -config $IBEAM_INPUTS_DIR/san.cnf -passout pass:"password"
                cat $IBEAM_INPUTS_DIR/key.pem $IBEAM_INPUTS_DIR/cert.pem > $IBEAM_INPUTS_DIR/cacert.pem
                openssl pkcs12 -export -in $IBEAM_INPUTS_DIR/cacert.pem -out $IBEAM_INPUTS_DIR/cacert.p12 -passin pass:'password' -passout pass:'password' 
                echo "password" | keytool -importkeystore -srckeystore $IBEAM_INPUTS_DIR/cacert.p12 -srcstoretype pkcs12 -destkeystore $IBEAM_INPUTS_DIR/cacert.jks -storepass password -deststoretype pkcs12 

                cp $IBEAM_INPUTS_DIR/key.pem /etc/ssl/certs/key.pem
                cp $IBEAM_INPUTS_DIR/cert.pem /etc/ssl/certs/cert.pem
            EOF
            chmod +x $IBEAM_INPUTS_DIR/generate-cert.sh

            cd $IBEAM_INPUTS_DIR
            PRIVATE_IPV4=$PRIVATE_IPV4 PRIVATE_HOSTNAME=$PRIVATE_HOSTNAME IBEAM_INPUTS_DIR=$IBEAM_INPUTS_DIR . $IBEAM_INPUTS_DIR/generate-cert.sh

            cat <<'EOF' > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent-schema.tmpl
              {
                "agent": {
                  "run_as_user": "root"
                },
                "logs": {
                  "logs_collected": {
                    "files": {
                      "collect_list": [
                        {
                          "file_path": "${!IBEAM_INPUTS_DIR}/logs/gw.*.log",
                          "log_group_name": "auto-invest-gateway-log",
                          "log_stream_name": "gateway-{instance_id}"
                        },
                        {
                          "file_path": "${!IBEAM_OUTPUTS_DIR}/*",
                          "log_group_name": "auto-invest-gateway-log",
                          "log_stream_name": "outputs-{instance_id}"
                        }                      
                      ]
                    }
                  }
                }
              }
            EOF

            IBEAM_INPUTS_DIR=$IBEAM_INPUTS_DIR IBEAM_OUTPUTS_DIR=$IBEAM_OUTPUTS_DIR envsubst < /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent-schema.tmpl > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent-schema.json
            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent-schema.json
            systemctl restart amazon-cloudwatch-agent

            docker pull $ECR_REGISTRY/$ECR_REPO:latest
            docker run \
                --env IBEAM_ACCOUNT=$IBEAM_ACCOUNT \
                --env IBEAM_PASSWORD=$IBEAM_PASSWORD \
                --env IBEAM_OUTPUTS_DIR=$IBEAM_OUTPUTS_DIR \
                --env IBEAM_INPUTS_DIR=$IBEAM_INPUTS_DIR \
                -v $IBEAM_OUTPUTS_DIR:$IBEAM_OUTPUTS_DIR \
                -v $IBEAM_INPUTS_DIR:$IBEAM_INPUTS_DIR \
                -p 5000:5000 $ECR_REGISTRY/$ECR_REPO

  GatewayLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${LogGroupPrefix}-gateway-log"
      RetentionInDays: !Ref LogRetention

  ApplicationLog:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${LogGroupPrefix}-application"
      RetentionInDays: !Ref LogRetention
      
  ScheduledActionOut: 
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      MaxSize: 1
      MinSize: 0
      Recurrence: "0 7 * * *"

  ScheduledActionIn: 
    Type: AWS::AutoScaling::ScheduledAction
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      MaxSize: 0
      MinSize: 0
      Recurrence: "0 19 * * *"
